application: noticiator2000
version: 1
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
